# Generated by Django 5.1.7 on 2025-04-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('User', models.CharField(max_length=30)),
                ('IPaddress', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
